
CREATE TABLE CAR_INFO(
MODEL_NUM INT AUTO_INCREMENT PRIMARY KEY 
, MODEL_NAME VARCHAR(50) NOT NULL
, PRICE INT NOT NULL
, MAKER VARCHAR(50) NOT NULL
)

sales_infoCREATE TABLE SALES_INFO(
SALES_NUM INT AUTO_INCREMENT PRIMARY KEY
, SALES_NAME VARCHAR(50) NOT NULL
, SALES_TEL VARCHAR(50)
, COLOR VARCHAR(50) NOT NULL
, SALES_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
, MODEL_NUM INT NOT NULL REFERENCES car_info(MODEL_NUM)
)
CREATE TABLE TEST_ITEM(
	ITEM_CODE INT AUTO_INCREMENT PRIMARY KEY
	, ITEM_NAME VARCHAR(30) NOT NULL
)

INSERT INTO TEST_ITEM VALUES (1, '상품1');
INSERT INTO TEST_ITEM VALUES (2, '상품2');
INSERT INTO TEST_ITEM VALUES (3, '상품3');

SELECT * FROM TEST_ITEM

CREATE TABLE TEST_ORDER(
	ORDER_NUM INT AUTO_INCREMENT PRIMARY KEY
	, BUYER VARCHAR(50) NOT NULL
	, ITEM_CODE INT NOT NULL REFERENCES TEST_ITEM(ITEM_CODE) ON DELETE CASCADE
)

car_info

INSERT INTO TEST_ORDER VALUES(1, '김자바', 1);
INSERT INTO TEST_ORDER VALUES(2, '김자바', 1);
INSERT INTO TEST_ORDER VALUES(3, '김자바', 2);

DELETE FROM  TEST_ITEM WHERE ITEM_CODE = 2


 INSERT INTO BOARD
  (TITLE
  , CONTENT
  , MEM_ID
  )
  VALUES
  ('테스트'
  , 'testststsststs'
  , 'java'
  )
	SELECT *
   FROM BOARD
   ORDER BY BOARD_NUM 
   
   LIMIT 5 OFFSET 0 -- 1PG
   LIMIT 5 OFFSET 5 -- 2PG
	LIMIT 5 OFFSET 10 -- 3PG
   -- LIMIT  OFFSET  페이징 처리를 위한 문법
	
	-- COUNT(컬럼명): 테이블에 존재하는  데이터 갯수 조회
	SELECT COUNT(BOARD_NUM) -- 왠만하면 pk로 넣어라 NULL이 잇으면 조회가 불가능하기에 
	FROM board  
